### ISSUE TITLE
Crawler: Collection idease for better text to the crawler questions

### ISSUE THREAD

**Issue by BioPhoton** [timdeschryver/find-deprecations#16]
- [x] tsConfigPath autosuggest exclude `node_modules`
- [x] suggest tags and/or branges
- [x] Better text of the end of a process and the start for a new one => setup, crawl
- [x] Optional processes with a question => do you want to group the deprecations
- [x] ~Process feedback/summary after it is done => list crawled number deprecations in number of files. List groups and number of related deprecations~ See. : #29 
- [x] ~After all processes are done give advice on further steps.~ See: #23 
- [x] make grouping a separate proess
- [x] Explain group name (relevant for the viewer, thing in headlines which become filenames e.g. `Internal use only` => `interna-use-only.md`)
- [x] Give more support on regex?
  - Readme with examples https://github.com/timdeschryver/find-deprecations/blob/master/lib/docs/example-config-rxjs.json#L5
  - Parse test string to lowercase => `([Ii])nternal` vs `internal`
  - Normalize whitespaces =>  `This  is` vs `This is`
  - Rephrase question e.g. "Which part of the deprecation message do you want to use as a matcher? Optionally paste a regex string"
- [x] ~More control of maintaining groups (delete group, rerun grouping)~ #23
